In [8]:
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd# Import Library
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import urllib.request
import datetime
from datetime import datetime
import nltk
from tqdm import tqdm
from nltk import word_tokenize
from nltk.corpus import PlaintextCorpusReader
from pandas_datareader import data as web
import os
import string
import requests
import datetime
import matplotlib.pyplot as plt
import urllib.request
import datetime
from datetime import datetime
import nltk
from tqdm import tqdm
from pandas_datareader import data as web
import os
import string
import requests
import datetime
import nltk
from nltk import word_tokenize
from nltk.corpus import PlaintextCorpusReader
from nltk.corpus import stopwords
from nltk.tokenize import TweetTokenizer
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import re
import string

In [66]:
Y = pd.read_csv("LabeledY.csv")
X = pd.read_csv("newscleaned2.csv")

In [67]:
Y.head()

,Unnamed: 0,Attributes,High,Low,Open,Close,Volume,Adj Close,Daily Growth,LabledY
0,2,2016-09-26,2158.540039,2145.040039,2158.540039,2146.100098,3216170000,2146.100098,-0.005763,-1
1,3,2016-09-27,2161.129883,2141.550049,2146.040039,2159.929932,3437770000,2159.929932,0.006472,1
2,4,2016-09-28,2172.399902,2151.790039,2161.850098,2171.370117,3891460000,2171.370117,0.004404,0
3,5,2016-09-29,2172.669922,2145.199951,2168.899902,2151.129883,4249220000,2151.129883,-0.008193,-1
4,6,2016-09-30,2175.300049,2156.510010,2156.510010,2168.270020,4173340000,2168.270020,0.005453,0

In [4]:
X.head()

,Unnamed: 0,Date,News_title,News_abstract
0,0,2016-09-26,additional skyhigh peres loss export lineup cr...,bare rescind prevent chemical include accompan...
1,1,2016-09-27,blunt restoration peres loss wealth list fisch...,version oppose loss export according list food...
2,2,2016-09-28,better lyft chemical peres loss knew robert li...,assuming chemical theatre loss export conducte...
3,3,2016-09-29,viral peres loss sound list credit pass rip la...,spurring mishandled export according transpare...
4,4,2016-09-30,peres loss reviewing list robert stance charlo...,fled version blunt persisted include peres los...

## Word2Vec

In [5]:
! pip install google-compute-engine

Requirement already satisfied: google-compute-engine in /usr/local/lib/python3.6/site-packages (2.8.3)
Requirement already satisfied: boto in /usr/local/lib/python3.6/site-packages (from google-compute-engine) (2.49.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from google-compute-engine) (28.8.0)
Requirement already satisfied: distro in /usr/local/lib/python3.6/site-packages (from google-compute-engine) (1.3.0)

In [6]:
! pip install boto

Requirement already satisfied: boto in /usr/local/lib/python3.6/site-packages (2.49.0)

In [15]:
from boto import plugin
from gensim.models import KeyedVectors
from gensim import matutils
from gensim.models import Word2Vec
import gensim

In [25]:
from textblob import TextBlob

In [37]:
a = X['News_title'][0]
# dd = pd.DataFrame()
# dd['polarity'] = TextBlob(a).sentiment[0]
# dd['subjectivity'] = TextBlob(a).sentiment[1]
b = TextBlob(a).sentiment[0]
c = TextBlob(a).sentiment[1]

In [47]:
X_score = pd.DataFrame()

In [48]:
# Polarity Analysis for news_title
X_score['title_polarity'] = X['News_title'].apply(lambda x: TextBlob(x).sentiment[0])
X_score['title_subjectivity'] = X['News_title'].apply(lambda x: TextBlob(x).sentiment[1])

# Polarity Analysis for news_abstract
X_score['abs_polarity'] = X['News_abstract'].apply(lambda x: TextBlob(x).sentiment[0])
X_score['abs_subjectivity'] = X['News_abstract'].apply(lambda x: TextBlob(x).sentiment[1])

In [49]:
X_score

     title_polarity  title_subjectivity  abs_polarity  abs_subjectivity
0          0.070004            0.396425      0.041043          0.413740
1          0.010467            0.412125      0.017999          0.435100
2          0.061586            0.368534      0.050819          0.481116
3          0.009768            0.415676      0.025399          0.419600
4          0.081814            0.429716      0.054197          0.412035
5          0.041357            0.350482      0.037696          0.396029
6          0.072068            0.377090      0.036085          0.420215
7         -0.006672            0.331287      0.021652          0.454649
8          0.069386            0.373315      0.013940          0.413580
9          0.072813            0.373992      0.060094          0.455539
10         0.054405            0.372891      0.023476          0.443727
11         0.051197            0.374065      0.052064          0.452809
12         0.064822            0.459450      0.034759          0.432353
13         0.084141            0.365783      0.039100          0.439922
14         0.095091            0.408496      0.053156          0.423356
15         0.057775            0.380156      0.025284          0.436036
16         0.048015            0.386387      0.064784          0.435945
17         0.039501            0.359079      0.044434          0.459512
18         0.028018            0.379150      0.027113          0.407808
19         0.108031            0.381328      0.036446          0.412242
20         0.018951            0.391115      0.045843          0.405277
21        -0.002102            0.395696      0.023865          0.418636
22         0.045184            0.377504      0.037596          0.439363
23         0.049049            0.414329      0.039026          0.442577
24         0.032207            0.382387      0.039436          0.450671
25         0.079676            0.401736      0.046898          0.425312
26         0.035178            0.389897      0.025765          0.445925
27         0.002226            0.455866      0.010887          0.454362
28         0.108770            0.345998      0.034734          0.423918
29         0.043022            0.420849      0.046110          0.442571
..              ...                 ...           ...               ...
478        0.022075            0.383183      0.029879          0.402881
479        0.063894            0.491941      0.066426          0.435689
480        0.089417            0.339376      0.081647          0.407686
481        0.054807            0.392799      0.074250          0.437124
482        0.091579            0.429797      0.059087          0.450512
483        0.015843            0.343677      0.025213          0.422333
484        0.052001            0.418443      0.063504          0.408473
485        0.067558            0.335772      0.053228          0.380037
486        0.054612            0.377848      0.073097          0.415157
487        0.005473            0.523740      0.024069          0.422124
488        0.120235            0.403543      0.112616          0.446079
489        0.017345            0.388628      0.055826          0.446574
490        0.099339            0.439906      0.090996          0.450592
491        0.077601            0.372867      0.035881          0.444529
492        0.030271            0.375352      0.058114          0.389805
493        0.055844            0.317068      0.025281          0.437008
494        0.067092            0.384840      0.075801          0.457047
495        0.069982            0.409931      0.019649          0.445861
496        0.061038            0.377823      0.084282          0.454824
497        0.089067            0.318719      0.018920          0.435233
498        0.040315            0.407630      0.040233          0.442225
499        0.103281            0.397190      0.026401          0.465851
500       -0.018856            0.415562      0.049422          0.429072
501        0.110196            0.435000      0.062325          0.445661
502        0.109302            0.363158      0.037779          0.402113
503        0.089312            0.449089      0.061971          0.463318
504        0.075767            0.342282      0.046624          0.445808
505       -0.001686            0.462444      0.055710          0.439409
506        0.068113            0.447525      0.067911          0.435112
507        0.026399            0.414284      0.060404          0.489558

[508 rows x 4 columns]

In [68]:
# Splite X to TrainX and TestX 70/30
# Splite Y to TrainY and TestY 70/30
Y = Y['LabledY']
cut = int(0.7*X.shape[0])
Xtrain = X.iloc[0: cut]
Xtest = X.iloc[X.shape[0]-cut:]
Ytrain = Y.iloc[0: cut]
Ytest = Y.iloc[Y.shape[0]-cut:]

In [70]:
from xgboost import XGBClassifier