In [7]:
import pandas as pd
#import index data
market_df = pd.read_csv("LabeledY.csv")[['Attributes', 'High','Low','Open','Close','Volume','Adj Close','Daily Growth','LabledY']]
market_df.head()

,Attributes,High,Low,Open,Close,Volume,Adj Close,Daily Growth,LabledY
0,2016-09-26,2158.540039,2145.040039,2158.540039,2146.100098,3216170000,2146.100098,-0.005763,-1
1,2016-09-27,2161.129883,2141.550049,2146.040039,2159.929932,3437770000,2159.929932,0.006472,1
2,2016-09-28,2172.399902,2151.790039,2161.850098,2171.370117,3891460000,2171.370117,0.004404,0
3,2016-09-29,2172.669922,2145.199951,2168.899902,2151.129883,4249220000,2151.129883,-0.008193,-1
4,2016-09-30,2175.300049,2156.510010,2156.510010,2168.270020,4173340000,2168.270020,0.005453,0

In [8]:
#Calculate Moving Average
market_df['7MA'] = market_df['Adj Close'].rolling(window=7).mean()
market_df['15MA'] = market_df['Adj Close'].rolling(window=15).mean()

,Attributes,High,Low,Open,Close,Volume,Adj Close,Daily Growth,LabledY,5MA
0,2016-09-26,2158.540039,2145.040039,2158.540039,2146.100098,3216170000,2146.100098,-0.005763,-1,NaN
1,2016-09-27,2161.129883,2141.550049,2146.040039,2159.929932,3437770000,2159.929932,0.006472,1,NaN
2,2016-09-28,2172.399902,2151.790039,2161.850098,2171.370117,3891460000,2171.370117,0.004404,0,NaN
3,2016-09-29,2172.669922,2145.199951,2168.899902,2151.129883,4249220000,2151.129883,-0.008193,-1,NaN
4,2016-09-30,2175.300049,2156.510010,2156.510010,2168.270020,4173340000,2168.270020,0.005453,0,2159.360010
5,2016-10-03,2164.409912,2154.770020,2164.330078,2161.199951,3137550000,2161.199951,-0.001446,0,2162.379980
6,2016-10-04,2165.459961,2144.010010,2163.370117,2150.489990,3750890000,2150.489990,-0.005954,-1,2160.491992
7,2016-10-05,2163.949951,2155.149902,2155.149902,2159.729980,3906550000,2159.729980,0.002125,0,2158.163965
8,2016-10-06,2162.929932,2150.280029,2158.219971,2160.770020,3461550000,2160.770020,0.001182,0,2160.091992
9,2016-10-07,2165.860107,2144.850098,2164.189941,2153.739990,3619890000,2153.739990,-0.004829,0,2157.185986
10,2016-10-10,2169.600098,2160.389893,2160.389893,2163.659912,2916550000,2163.659912,0.001514,0,2157.677979
11,2016-10-11,2161.560059,2128.840088,2161.350098,2136.729980,3438270000,2136.729980,-0.011391,-1,2154.925977
12,2016-10-12,2145.360107,2132.770020,2137.669922,2139.179932,2977100000,2139.179932,0.000706,0,2150.815967
13,2016-10-13,2138.189941,2114.719971,2130.260010,2132.550049,3580450000,2132.550049,0.001075,0,2145.171973
14,2016-10-14,2149.189941,2132.979980,2139.679932,2132.979980,3228150000,2132.979980,-0.003131,0,2141.019971
15,2016-10-17,2135.610107,2124.429932,2132.949951,2126.500000,2830390000,2126.500000,-0.003024,0,2133.587988
16,2016-10-18,2144.379883,2135.489990,2138.310059,2139.600098,3170000000,2139.600098,0.000603,0,2134.162012
17,2016-10-19,2148.439941,2138.149902,2140.810059,2144.290039,3362670000,2144.290039,0.001626,0,2135.184033
18,2016-10-20,2147.179932,2133.439941,2142.510010,2141.340088,3337170000,2141.340088,-0.000546,0,2136.942041
19,2016-10-21,2142.629883,2130.090088,2139.429932,2141.159912,3448850000,2141.159912,0.000809,0,2138.578027
20,2016-10-24,2154.790039,2146.909912,2148.500000,2151.330078,3357320000,2151.330078,0.001317,0,2143.544043
21,2016-10-25,2151.439941,2141.929932,2149.719971,2143.159912,3751340000,2143.159912,-0.003052,0,2144.256006
22,2016-10-26,2145.729980,2131.590088,2136.969971,2139.429932,3775200000,2139.429932,0.001151,0,2143.283984
23,2016-10-27,2147.129883,2132.520020,2144.060059,2133.040039,4204830000,2133.040039,-0.005140,0,2141.623975
24,2016-10-28,2140.719971,2119.360107,2132.229980,2126.409912,4019510000,2126.409912,-0.002730,0,2138.673975
25,2016-10-31,2133.250000,2125.530029,2129.780029,2126.149902,3922400000,2126.149902,-0.001704,0,2133.637939
26,2016-11-01,2131.449951,2097.850098,2128.679932,2111.719971,4532160000,2111.719971,-0.007967,-1,2127.349951
27,2016-11-02,2111.760010,2094.000000,2109.429932,2097.939941,4248580000,2097.939941,-0.005447,0,2119.051953
28,2016-11-03,2102.560059,2085.229980,2098.800049,2088.659912,3886740000,2088.659912,-0.004831,0,2110.175928
29,2016-11-04,2099.070068,2083.790039,2083.790039,2085.179932,3837860000,2085.179932,0.000667,0,2101.929932
...,...,...,...,...,...,...,...,...,...,...
478,2018-08-20,2859.760010,2850.620117,2853.929932,2857.050049,2748020000,2857.050049,0.001093,0,2841.239990
479,2018-08-21,2873.229980,2861.320068,2861.510010,2862.959961,3147140000,2862.959961,0.000507,0,2845.839990
480,2018-08-22,2867.540039,2856.050049,2860.989990,2861.820068,2689560000,2861.820068,0.000290,0,2854.529980
481,2018-08-23,2868.780029,2854.030029,2860.290039,2856.979980,2713910000,2856.979980,-0.001157,0,2857.787988
482,2018-08-24,2876.159912,2862.350098,2862.350098,2874.689941,2596190000,2874.689941,0.004311,0,2862.700000
483,2018-08-27,2898.250000,2884.689941,2884.689941,2896.739990,2854080000,2896.739990,0.004177,0,2870.637988
484,2018-08-28,2903.770020,2893.500000,2901.449951,2897.520020,2683190000,2897.520020,-0.001354,0,2877.550000
485,2018-08-29,2916.500000,2898.399902,2900.620117,2914.040039,2791860000,2914.040039,0.004627,0,2887.993994
486,2018-08-30,2912.459961,2895.219971,2908.939941,2901.129883,2802180000,2901.129883,-0.002685,0,2896.823975
487,2018-08-31,2906.320068,2891.729980,2898.370117,2901.520020,2880260000,2901.520020,0.001087,0,2902.189990
488,2018-09-04,2900.179932,2885.129883,2896.959961,2896.719971,3077060000,2896.719971,-0.000083,0,2902.185986
489,2018-09-05,2894.209961,2876.919922,2891.590088,2888.600098,3241250000,2888.600098,-0.001034,0,2900.402002
490,2018-09-06,2892.050049,2867.290039,2888.639893,2878.050049,3139590000,2878.050049,-0.003666,0,2893.204004
491,2018-09-07,2883.810059,2864.120117,2868.260010,2871.679932,2946270000,2871.679932,0.001192,0,2887.314014
492,2018-09-10,2886.929932,2875.939941,2881.389893,2877.129883,2731400000,2877.129883,-0.001478,0,2882.435986
493,2018-09-11,2892.520020,2866.780029,2871.570068,2887.889893,2899660000,2887.889893,0.005683,0,2880.669971
494,2018-09-12,2894.649902,2879.199951,2888.290039,2888.919922,3264930000,2888.919922,0.000218,0,2880.733936
495,2018-09-13,2906.760010,2896.389893,2896.850098,2904.179932,3254930000,2904.179932,0.002530,0,2885.959912
496,2018-09-14,2908.300049,2895.770020,2906.379883,2904.979980,3149800000,2904.979980,-0.000482,0,2892.619922
497,2018-09-17,2904.649902,2886.159912,2903.830078,2888.800049,2947760000,2888.800049,-0.005176,0,2894.953955
498,2018-09-18,2911.169922,2890.429932,2890.739990,2904.310059,3074610000,2904.310059,0.004694,0,2898.237988
499,2018-09-19,2912.360107,2903.820068,2906.600098,2907.949951,3280020000,2907.949951,0.000464,0,2902.043994
500,2018-09-20,2934.800049,2919.729980,2919.729980,2930.750000,3337730000,2930.750000,0.003774,0,2907.358008
501,2018-09-21,2940.909912,2927.110107,2936.760010,2929.669922,5607610000,2929.669922,-0.002414,0,2912.295996
502,2018-09-24,2923.790039,2912.629883,2921.830078,2919.370117,3372210000,2919.370117,-0.000842,0,2918.410010
503,2018-09-25,2923.949951,2913.699951,2921.750000,2915.560059,3285480000,2915.560059,-0.002119,0,2920.660010
504,2018-09-26,2931.149902,2903.280029,2916.979980,2905.969971,3388620000,2905.969971,-0.003774,0,2920.264014
505,2018-09-27,2927.219971,2909.270020,2911.649902,2914.000000,3060850000,2914.000000,0.000807,0,2916.914014
506,2018-09-28,2920.530029,2907.500000,2910.030029,2913.979980,3432300000,2913.979980,0.001357,0,2913.776025
507,2018-10-01,2937.060059,2917.909912,2926.290039,2924.590088,3364190000,2924.590088,-0.000581,0,2914.820020